version: '0.1'
services:
  gallery-eureka:
    image: gallery-cloud/gallery-eureka:0.1
    hostname: gallery-eureka
    ports:
      - "8761:8761"
  gallery-gateway:
    image: gallery-cloud/gallery-gateway:0.1
    hostname: gallery-gateway
    links:
      - gallery-eureka
      - gallery-user-service
#      - gallery-image-service
      - gallery-file-service
    ports:
      - "6200:6200"
  gallery-hystrix-dashboard:
    image: gallery-cloud/gallery-hystrix-dashboard:0.1
    hostname: gallery-hystrix-dashboard
    links:
      - gallery-eureka
    ports:
      - "8762:8762"
  gallery-user-service:
    image: gallery-cloud/gallery-user-service:0.1
    links:
      - gallery-eureka
    hostname: gallery-user-service
#  gallery-image-service:
#    image: gallery-cloud/gallery-image-service:0.1
#    links:
#      - gallery-eureka
#    hostname: gallery-image-service
#    ports:
#      - "6002:6002"
  gallery-file-service:
    image: gallery-cloud/gallery-file-service:0.1
    links:
      - gallery-eureka
    hostname: gallery-file-service
    ports:
      - "6003:6003"
#  gallery-turbine:
#    image: gallery-cloud/gallery-turbine
#      hostname: gallery-turbine
#      ports:
#      - "8761:8761"